application:
  port: 8000
  host: 0.0.0.0
  hmac_secret: "QfTjWnZr4u7w!z%C*F-JaNdRgUkXp2s5v8y/A?D(G+KbPeShVmYq3t6w9z$C&E)H"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "traders"
  require_ssl: false
test:
  secret_key: "2s5v8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x!A%D*G-KaPdSgV"
redis_uri: "redis://127.0.0.1:6379"
